### ISSUE TITLE
Error in aunty new

### ISSUE THREAD

**Issue by phocks** [abcnews/aunty#140]
Just thought I'd bring up this issue I seem to be getting when starting new projects in aunty

```
✖ Error: Command failed with exit code 1: npm install --silent --no-progress --save-dev @abcnews/aunty@11.2.0 @types/jest @types/webpack-env
    at makeError (/Users/byrdj5d/.config/yarn/global/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/byrdj5d/.config/yarn/global/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async module.exports.installDependencies (/Users/byrdj5d/.config/yarn/global/node_modules/@abcnews/aunty/src/utils/npm.js:55:3)
    at async module.exports.install (/Users/byrdj5d/.config/yarn/global/node_modules/@abcnews/aunty/src/generators/project/index.js:187:5) {
  shortMessage: 'Command failed with exit code 1: npm install --silent --no-progress --save-dev @abcnews/aunty@11.2.0 @types/jest @types/webpack-env',
  command: 'npm install --silent --no-progress --save-dev @abcnews/aunty@11.2.0 @types/jest @types/webpack-env',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

I seem to be able to fix it by doing this: `npm install --save-dev @abcnews/aunty@latest`

**Comment by drzax** [comment]
@phocks is this still a problem?

**Comment by phocks** [comment]
Nope, all good now.
