### ISSUE TITLE
Upgrade to aunty 12.1.0 giving aunty serve devserver error

### ISSUE THREAD

**Issue by phocks** [abcnews/aunty#155]
Updated to 12.1.0 and now `aunty serve` seems to be giving me this. I'm running a svelte project.

```
ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options.server.options should be an object:
   object { passphrase?, requestCert?, ca?, cacert?, cert?, crl?, key?, pfx?, … }
    at validate (/Users/byrdj5d/Sites/interactive-deeptime/node_modules/webpack-dev-server/node_modules/schema-utils/dist/validate.js:115:11)
    at new Server (/Users/byrdj5d/Sites/interactive-deeptime/node_modules/webpack-dev-server/lib/Server.js:31:5)
    at Object.construct (/Users/byrdj5d/Sites/interactive-deeptime/node_modules/import-lazy/index.js:20:20)
    at /Users/byrdj5d/Sites/interactive-deeptime/node_modules/@abcnews/aunty/src/cli/serve/index.js:78:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/byrdj5d/Sites/interactive-deeptime/node_modules/@abcnews/aunty/src/cli/index.js:144:17
    at async /Users/byrdj5d/Sites/interactive-deeptime/node_modules/@abcnews/aunty/src/cli/index.js:78:10
    at async /Users/byrdj5d/Sites/interactive-deeptime/node_modules/@abcnews/aunty/src/bin/aunty.js:23:19 {
```

Unsure but it may be related to this https://stackoverflow.com/a/62680933/955917

**Comment by colingourlay** [comment]
This should be fixed in `12.1.1`, which doesn't provide a `server` object at all if we don't have a locally generated HTTPS cert. It turns out that `{ type: 'https', options: null }` isn't acceptable.
