### ISSUE TITLE
RpcIpcMessagePortClosedError when running `npm run test`

### ISSUE THREAD

**Issue by phocks** [abcnews/aunty#216]
I'm getting:

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 95386.
    at /Users/byrd.joshua/src/aunty/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: undefined,
  signal: undefined
}

Node.js v18.18.2
[15:20:05] [~/src/aunty] [main] ❱❱❱ node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

RpcIpcMessagePortClosedError: Cannot send the message - the message port has been closed for the process 95385.
    at /Users/byrd.joshua/src/aunty/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/rpc-ipc/RpcIpcMessagePort.js:47:47
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
  code: undefined,
  signal: undefined
}

Node.js v18.18.2
```

When I run `npm run test` on main branch.

**Comment by phocks** [comment]
OK I updated to Node ^20 and the problem went away.
